[package]
name = "markdown"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
iced = { workspace = true, features = ["markdown", "highlighter", "image", "tokio", "debug", "winit"] }

reqwest = { version = "0.12", features = ["json"] }

tokio = { workspace = true, features = ["fs"] }

image = { workspace = true }
url = { workspace = true }

webbrowser = "1"

# Disabled to keep amount of build dependencies low
# This can be re-enabled on demand
# [build-dependencies]
# iced_fontello = "0.13"
